// =========================================================================
// The ידיעון's exam slots and paper deadlines, as the app reads them
// =========================================================================
// Backed by src/data/yedion-5787-assessments.json, generated by
// scripts/parse-yedion-assessments.ts from the ידיעון's own "לוח בחינות
// ומטלות" page. See that script's header for what the source does and does not
// contain — the short version:
//
//   · exam sittings come with a DAY and a TIME, and no date. The ידיעון has
//     not published תשפ״ז exam dates yet.
//   · assignment deadlines come with real dates.
//
// This module exists so the app can finally say something true and useful about
// an exam whose date is unknown: "מועד א׳ ביום ד׳ ב-14:00, התאריך טרם פורסם"
// is a great deal more helpful than "טרם פורסם" alone, and it is fully sourced.
//
// It never fabricates a date. If a student needs the date, the honest answer is
// still that the university hasn't set it.
import raw from "@/data/yedion-5787-assessments.json";

export interface YedionSitting {
  sitting: "A" | "B";
  dayOfWeek: string;
  time: string;
}

export interface YedionAssessment {
  courseCode: string;
  group: string | null;
  kind: "exam" | "paper" | "unknown";
  sittings: YedionSitting[];
  dueDate: string | null;
}

const RECORDS = (raw as { records: YedionAssessment[] }).records;

/** Index by course code. A course can appear once per group. */
const BY_CODE = new Map<string, YedionAssessment[]>();
for (const r of RECORDS) {
  const list = BY_CODE.get(r.courseCode);
  if (list) list.push(r);
  else BY_CODE.set(r.courseCode, [r]);
}

/** Everything the ידיעון says about this course's assessment. */
export function assessmentsFor(courseCode: string | null | undefined): YedionAssessment[] {
  if (!courseCode) return [];
  return BY_CODE.get(courseCode.trim()) ?? [];
}

/**
 * The exam sittings for a course — day and time only.
 *
 * Prefers the record matching the student's group; falls back to a
 * "כל הקבוצות" record, then to any exam record for the course. Different
 * groups of the same course really can sit at different times, so the group
 * match matters and is tried first.
 */
export function examSittingsFor(
  courseCode: string | null | undefined,
  group?: string | null,
): YedionSitting[] {
  const exams = assessmentsFor(courseCode).filter((r) => r.kind === "exam" && r.sittings.length > 0);
  if (exams.length === 0) return [];
  const exact = group ? exams.find((r) => r.group === group) : undefined;
  const all = exams.find((r) => r.group === "כל הקבוצות");
  return (exact ?? all ?? exams[0]!).sittings;
}

/** The paper deadline (ISO) the ידיעון prints for this course, if any. */
export function paperDeadlineFor(
  courseCode: string | null | undefined,
  group?: string | null,
): string | null {
  const papers = assessmentsFor(courseCode).filter((r) => r.kind === "paper" && r.dueDate);
  if (papers.length === 0) return null;
  const exact = group ? papers.find((r) => r.group === group) : undefined;
  const all = papers.find((r) => r.group === "כל הקבוצות");
  return (exact ?? all ?? papers[0]!).dueDate;
}

const DAY_HE: Record<string, string> = {
  SUNDAY: "ראשון", MONDAY: "שני", TUESDAY: "שלישי",
  WEDNESDAY: "רביעי", THURSDAY: "חמישי", FRIDAY: "שישי",
};

/**
 * "מועד א׳ · יום רביעי, 14:00" — what we CAN say when the date is unknown.
 * Returns null rather than a half-sentence when we know nothing.
 */
export function describeSitting(s: YedionSitting, isHe = true): string {
  const label = isHe
    ? s.sitting === "A" ? "מועד א׳" : "מועד ב׳"
    : s.sitting === "A" ? "1st sitting" : "2nd sitting";
  if (isHe) return `${label} · יום ${DAY_HE[s.dayOfWeek] ?? ""}, ${s.time}`;
  const en = s.dayOfWeek.charAt(0) + s.dayOfWeek.slice(1).toLowerCase();
  return `${label} · ${en}, ${s.time}`;
}

/** How much of the catalog this data actually covers — for honest reporting. */
export function coverage(): { exams: number; papers: number; examsWithDate: number } {
  return {
    exams: RECORDS.filter((r) => r.kind === "exam" && r.sittings.length > 0).length,
    papers: RECORDS.filter((r) => r.kind === "paper" && r.dueDate).length,
    // Always ~0: the ידיעון does not publish תשפ״ז exam dates.
    examsWithDate: RECORDS.filter((r) => r.kind === "exam" && r.dueDate).length,
  };
}
