import { openApp, login, shot, BASE } from "./tour-lib.mjs";
const { b, p, errors } = await openApp();
await login(p); await p.waitForTimeout(5000);
await p.goto(`${BASE}/he/planner`,{waitUntil:"networkidle"}); await p.waitForTimeout(6000);
const link = p.getByRole("link",{name:/תכננו את שני הסמסטרים|לעריכת התכנון/}).first();
const btn  = p.getByRole("button",{name:/תכננו את שני הסמסטרים|לעריכת התכנון/}).first();
if (await link.count()) await link.click(); else if (await btn.count()) await btn.click();
await p.waitForTimeout(8000);
const t=(await p.locator("body").innerText()).replace(/\n+/g," | ");
const i=t.indexOf("החלטות גדולות.");
console.log("URL:", p.url().replace(BASE,""));
console.log("על המסך:", t.slice(i+16,i+330));
console.log("\nמסך סיכום?", /המערכת המומלצת מוכנה/.test(t) ? "✗ עדיין סיכום" : "✓ לא");
console.log("עורך עם טאבים?", /סמסטר א׳|סמסטר ב׳/.test(t) && /הוסיפו קורס|בריכת|הוספה/.test(t) ? "✓ כן" : "?");
const tabs = await p.evaluate(()=>[...document.querySelectorAll("button")].map(x=>x.innerText.trim().replace(/\n/g," ")).filter(x=>/^סמסטר [אב]׳/.test(x)));
console.log("טאבי הסמסטרים:", JSON.stringify(tabs));
console.log(await shot(p,"L2-verified"));
console.log("שגיאות:", errors.length?[...new Set(errors)].join(" | "):"אין");
await b.close();
