import { chromium } from "playwright";
const OUT="/private/tmp/claude-502/-Users-Ariel----------------6-----------------------/0e4fb0f3-f1be-4ee8-875b-02173d94910a/scratchpad/pass2";
const BASE="https://pakam-strategist.vercel.app";
const say=console.log;
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:1000},locale:"he-IL",timezoneId:"Asia/Jerusalem"});
const p=await ctx.newPage();
await p.goto(`${BASE}/he/login`,{waitUntil:"networkidle"});
await p.getByRole("button",{name:/התחברות עם דוא/}).click();
await p.locator('input[type=email]').fill("test@pakamon.dev");
await p.locator('input[type=password]').fill("test123456");
await p.locator('button[type=submit]').click();
await p.waitForURL(/dashboard/,{timeout:45000});
await p.waitForFunction(()=>document.body.innerText.length>900, null,{timeout:60000});
await p.waitForTimeout(3500);
const go=p.getByRole("button",{name:/בואו נתחיל/}).first();
if(await go.count()){await go.click();await p.waitForTimeout(3000);}
await p.locator('text=/כבר יש לכם ש/').first().click(); await p.waitForTimeout(4000);
await p.locator('input[type=file]').first().setInputFiles(`${OUT}/sheet.png`);
await p.waitForFunction(()=>/קראנו \d+ קורסים/.test(document.body.innerText), null,{timeout:120000});
say("✅ נסרק");
await p.getByRole("button",{name:/נכון — המשיכו/}).first().click();
await p.waitForTimeout(7000);
const t=(await p.locator("body").innerText()).replace(/\n+/g," | ");
const i=t.indexOf("אנגלית");
say("── האנגלית במסך הפרופיל ──");
say(t.slice(Math.max(0,i-260), i+520));
await p.screenshot({path:`${OUT}/06-english.png`,fullPage:true});
await b.close();
