import { chromium } from "playwright";
const BASE="https://pakam-strategist.vercel.app";
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:1000},locale:"he-IL",timezoneId:"Asia/Jerusalem"});
const p=await ctx.newPage();
const errs=[]; p.on("pageerror",e=>errs.push(String(e).slice(0,110)));
await p.goto(`${BASE}/he/login`,{waitUntil:"networkidle"});
await p.getByRole("button",{name:/התחברות עם דוא/}).click();
await p.locator('input[type=email]').fill("test@pakamon.dev");
await p.locator('input[type=password]').fill("test123456");
await p.locator('button[type=submit]').click();
await p.waitForURL(/dashboard/,{timeout:45000}); await p.waitForTimeout(8000);
const t=(await p.locator("body").innerText()).replace(/\n+/g," | ");
console.log("=== מה שסטודנט חדש רואה בבוקר ההשקה ===");
console.log(t.slice(0,900));
console.log("\nהאשף נפתח:", /בחרו תוכנית|באיזו שנה|ברוכים|נתחיל|בואו נתחיל/.test(t) ? "✓" : "✗");
console.log("כרטיס 'אין קורסים' (לא אמור להופיע כאן):", t.includes("אין קורסים בתוכנית שלכם") ? "✗ מופיע" : "✓ לא מופיע");
console.log("שגיאות:", errs.length?[...new Set(errs)].join(" | "):"אין");
await b.close();
